
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Store` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Store
 * 
 */
export type StoreModel = runtime.Types.Result.DefaultSelection<Prisma.$StorePayload>

export type AggregateStore = {
  _count: StoreCountAggregateOutputType | null
  _min: StoreMinAggregateOutputType | null
  _max: StoreMaxAggregateOutputType | null
}

export type StoreMinAggregateOutputType = {
  id: string | null
  userId: string | null
  name: string | null
  description: string | null
  username: string | null
  address: string | null
  status: string | null
  isActive: boolean | null
  logo: string | null
  email: string | null
  contact: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StoreMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  name: string | null
  description: string | null
  username: string | null
  address: string | null
  status: string | null
  isActive: boolean | null
  logo: string | null
  email: string | null
  contact: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StoreCountAggregateOutputType = {
  id: number
  userId: number
  name: number
  description: number
  username: number
  address: number
  status: number
  isActive: number
  logo: number
  email: number
  contact: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type StoreMinAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  description?: true
  username?: true
  address?: true
  status?: true
  isActive?: true
  logo?: true
  email?: true
  contact?: true
  createdAt?: true
  updatedAt?: true
}

export type StoreMaxAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  description?: true
  username?: true
  address?: true
  status?: true
  isActive?: true
  logo?: true
  email?: true
  contact?: true
  createdAt?: true
  updatedAt?: true
}

export type StoreCountAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  description?: true
  username?: true
  address?: true
  status?: true
  isActive?: true
  logo?: true
  email?: true
  contact?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type StoreAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Store to aggregate.
   */
  where?: Prisma.StoreWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stores to fetch.
   */
  orderBy?: Prisma.StoreOrderByWithRelationInput | Prisma.StoreOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StoreWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Stores
  **/
  _count?: true | StoreCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StoreMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StoreMaxAggregateInputType
}

export type GetStoreAggregateType<T extends StoreAggregateArgs> = {
      [P in keyof T & keyof AggregateStore]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStore[P]>
    : Prisma.GetScalarType<T[P], AggregateStore[P]>
}




export type StoreGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StoreWhereInput
  orderBy?: Prisma.StoreOrderByWithAggregationInput | Prisma.StoreOrderByWithAggregationInput[]
  by: Prisma.StoreScalarFieldEnum[] | Prisma.StoreScalarFieldEnum
  having?: Prisma.StoreScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StoreCountAggregateInputType | true
  _min?: StoreMinAggregateInputType
  _max?: StoreMaxAggregateInputType
}

export type StoreGroupByOutputType = {
  id: string
  userId: string
  name: string
  description: string
  username: string
  address: string
  status: string
  isActive: boolean
  logo: string
  email: string
  contact: string
  createdAt: Date
  updatedAt: Date
  _count: StoreCountAggregateOutputType | null
  _min: StoreMinAggregateOutputType | null
  _max: StoreMaxAggregateOutputType | null
}

type GetStoreGroupByPayload<T extends StoreGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StoreGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StoreGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StoreGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StoreGroupByOutputType[P]>
      }
    >
  >



export type StoreWhereInput = {
  AND?: Prisma.StoreWhereInput | Prisma.StoreWhereInput[]
  OR?: Prisma.StoreWhereInput[]
  NOT?: Prisma.StoreWhereInput | Prisma.StoreWhereInput[]
  id?: Prisma.StringFilter<"Store"> | string
  userId?: Prisma.StringFilter<"Store"> | string
  name?: Prisma.StringFilter<"Store"> | string
  description?: Prisma.StringFilter<"Store"> | string
  username?: Prisma.StringFilter<"Store"> | string
  address?: Prisma.StringFilter<"Store"> | string
  status?: Prisma.StringFilter<"Store"> | string
  isActive?: Prisma.BoolFilter<"Store"> | boolean
  logo?: Prisma.StringFilter<"Store"> | string
  email?: Prisma.StringFilter<"Store"> | string
  contact?: Prisma.StringFilter<"Store"> | string
  createdAt?: Prisma.DateTimeFilter<"Store"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Store"> | Date | string
  Product?: Prisma.ProductListRelationFilter
  Order?: Prisma.OrderListRelationFilter
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type StoreOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  username?: Prisma.SortOrder
  address?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  logo?: Prisma.SortOrder
  email?: Prisma.SortOrder
  contact?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  Product?: Prisma.ProductOrderByRelationAggregateInput
  Order?: Prisma.OrderOrderByRelationAggregateInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type StoreWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  username?: string
  AND?: Prisma.StoreWhereInput | Prisma.StoreWhereInput[]
  OR?: Prisma.StoreWhereInput[]
  NOT?: Prisma.StoreWhereInput | Prisma.StoreWhereInput[]
  name?: Prisma.StringFilter<"Store"> | string
  description?: Prisma.StringFilter<"Store"> | string
  address?: Prisma.StringFilter<"Store"> | string
  status?: Prisma.StringFilter<"Store"> | string
  isActive?: Prisma.BoolFilter<"Store"> | boolean
  logo?: Prisma.StringFilter<"Store"> | string
  email?: Prisma.StringFilter<"Store"> | string
  contact?: Prisma.StringFilter<"Store"> | string
  createdAt?: Prisma.DateTimeFilter<"Store"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Store"> | Date | string
  Product?: Prisma.ProductListRelationFilter
  Order?: Prisma.OrderListRelationFilter
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId" | "username">

export type StoreOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  username?: Prisma.SortOrder
  address?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  logo?: Prisma.SortOrder
  email?: Prisma.SortOrder
  contact?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.StoreCountOrderByAggregateInput
  _max?: Prisma.StoreMaxOrderByAggregateInput
  _min?: Prisma.StoreMinOrderByAggregateInput
}

export type StoreScalarWhereWithAggregatesInput = {
  AND?: Prisma.StoreScalarWhereWithAggregatesInput | Prisma.StoreScalarWhereWithAggregatesInput[]
  OR?: Prisma.StoreScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StoreScalarWhereWithAggregatesInput | Prisma.StoreScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Store"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Store"> | string
  name?: Prisma.StringWithAggregatesFilter<"Store"> | string
  description?: Prisma.StringWithAggregatesFilter<"Store"> | string
  username?: Prisma.StringWithAggregatesFilter<"Store"> | string
  address?: Prisma.StringWithAggregatesFilter<"Store"> | string
  status?: Prisma.StringWithAggregatesFilter<"Store"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"Store"> | boolean
  logo?: Prisma.StringWithAggregatesFilter<"Store"> | string
  email?: Prisma.StringWithAggregatesFilter<"Store"> | string
  contact?: Prisma.StringWithAggregatesFilter<"Store"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Store"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Store"> | Date | string
}

export type StoreCreateInput = {
  id?: string
  name: string
  description: string
  username: string
  address: string
  status?: string
  isActive?: boolean
  logo: string
  email: string
  contact: string
  createdAt?: Date | string
  updatedAt?: Date | string
  Product?: Prisma.ProductCreateNestedManyWithoutStoreInput
  Order?: Prisma.OrderCreateNestedManyWithoutStoreInput
  user: Prisma.UserCreateNestedOneWithoutStoreInput
}

export type StoreUncheckedCreateInput = {
  id?: string
  userId: string
  name: string
  description: string
  username: string
  address: string
  status?: string
  isActive?: boolean
  logo: string
  email: string
  contact: string
  createdAt?: Date | string
  updatedAt?: Date | string
  Product?: Prisma.ProductUncheckedCreateNestedManyWithoutStoreInput
  Order?: Prisma.OrderUncheckedCreateNestedManyWithoutStoreInput
}

export type StoreUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logo?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Product?: Prisma.ProductUpdateManyWithoutStoreNestedInput
  Order?: Prisma.OrderUpdateManyWithoutStoreNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutStoreNestedInput
}

export type StoreUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logo?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Product?: Prisma.ProductUncheckedUpdateManyWithoutStoreNestedInput
  Order?: Prisma.OrderUncheckedUpdateManyWithoutStoreNestedInput
}

export type StoreCreateManyInput = {
  id?: string
  userId: string
  name: string
  description: string
  username: string
  address: string
  status?: string
  isActive?: boolean
  logo: string
  email: string
  contact: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StoreUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logo?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logo?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreNullableScalarRelationFilter = {
  is?: Prisma.StoreWhereInput | null
  isNot?: Prisma.StoreWhereInput | null
}

export type StoreScalarRelationFilter = {
  is?: Prisma.StoreWhereInput
  isNot?: Prisma.StoreWhereInput
}

export type StoreCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  username?: Prisma.SortOrder
  address?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  logo?: Prisma.SortOrder
  email?: Prisma.SortOrder
  contact?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StoreMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  username?: Prisma.SortOrder
  address?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  logo?: Prisma.SortOrder
  email?: Prisma.SortOrder
  contact?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StoreMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  username?: Prisma.SortOrder
  address?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  logo?: Prisma.SortOrder
  email?: Prisma.SortOrder
  contact?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StoreCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StoreCreateWithoutUserInput, Prisma.StoreUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StoreCreateOrConnectWithoutUserInput
  connect?: Prisma.StoreWhereUniqueInput
}

export type StoreUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StoreCreateWithoutUserInput, Prisma.StoreUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StoreCreateOrConnectWithoutUserInput
  connect?: Prisma.StoreWhereUniqueInput
}

export type StoreUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StoreCreateWithoutUserInput, Prisma.StoreUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StoreCreateOrConnectWithoutUserInput
  upsert?: Prisma.StoreUpsertWithoutUserInput
  disconnect?: Prisma.StoreWhereInput | boolean
  delete?: Prisma.StoreWhereInput | boolean
  connect?: Prisma.StoreWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StoreUpdateToOneWithWhereWithoutUserInput, Prisma.StoreUpdateWithoutUserInput>, Prisma.StoreUncheckedUpdateWithoutUserInput>
}

export type StoreUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StoreCreateWithoutUserInput, Prisma.StoreUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StoreCreateOrConnectWithoutUserInput
  upsert?: Prisma.StoreUpsertWithoutUserInput
  disconnect?: Prisma.StoreWhereInput | boolean
  delete?: Prisma.StoreWhereInput | boolean
  connect?: Prisma.StoreWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StoreUpdateToOneWithWhereWithoutUserInput, Prisma.StoreUpdateWithoutUserInput>, Prisma.StoreUncheckedUpdateWithoutUserInput>
}

export type StoreCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.StoreCreateWithoutProductInput, Prisma.StoreUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.StoreCreateOrConnectWithoutProductInput
  connect?: Prisma.StoreWhereUniqueInput
}

export type StoreUpdateOneRequiredWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.StoreCreateWithoutProductInput, Prisma.StoreUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.StoreCreateOrConnectWithoutProductInput
  upsert?: Prisma.StoreUpsertWithoutProductInput
  connect?: Prisma.StoreWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StoreUpdateToOneWithWhereWithoutProductInput, Prisma.StoreUpdateWithoutProductInput>, Prisma.StoreUncheckedUpdateWithoutProductInput>
}

export type StoreCreateNestedOneWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.StoreCreateWithoutOrderInput, Prisma.StoreUncheckedCreateWithoutOrderInput>
  connectOrCreate?: Prisma.StoreCreateOrConnectWithoutOrderInput
  connect?: Prisma.StoreWhereUniqueInput
}

export type StoreUpdateOneRequiredWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.StoreCreateWithoutOrderInput, Prisma.StoreUncheckedCreateWithoutOrderInput>
  connectOrCreate?: Prisma.StoreCreateOrConnectWithoutOrderInput
  upsert?: Prisma.StoreUpsertWithoutOrderInput
  connect?: Prisma.StoreWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StoreUpdateToOneWithWhereWithoutOrderInput, Prisma.StoreUpdateWithoutOrderInput>, Prisma.StoreUncheckedUpdateWithoutOrderInput>
}

export type StoreCreateWithoutUserInput = {
  id?: string
  name: string
  description: string
  username: string
  address: string
  status?: string
  isActive?: boolean
  logo: string
  email: string
  contact: string
  createdAt?: Date | string
  updatedAt?: Date | string
  Product?: Prisma.ProductCreateNestedManyWithoutStoreInput
  Order?: Prisma.OrderCreateNestedManyWithoutStoreInput
}

export type StoreUncheckedCreateWithoutUserInput = {
  id?: string
  name: string
  description: string
  username: string
  address: string
  status?: string
  isActive?: boolean
  logo: string
  email: string
  contact: string
  createdAt?: Date | string
  updatedAt?: Date | string
  Product?: Prisma.ProductUncheckedCreateNestedManyWithoutStoreInput
  Order?: Prisma.OrderUncheckedCreateNestedManyWithoutStoreInput
}

export type StoreCreateOrConnectWithoutUserInput = {
  where: Prisma.StoreWhereUniqueInput
  create: Prisma.XOR<Prisma.StoreCreateWithoutUserInput, Prisma.StoreUncheckedCreateWithoutUserInput>
}

export type StoreUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.StoreUpdateWithoutUserInput, Prisma.StoreUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.StoreCreateWithoutUserInput, Prisma.StoreUncheckedCreateWithoutUserInput>
  where?: Prisma.StoreWhereInput
}

export type StoreUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.StoreWhereInput
  data: Prisma.XOR<Prisma.StoreUpdateWithoutUserInput, Prisma.StoreUncheckedUpdateWithoutUserInput>
}

export type StoreUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logo?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Product?: Prisma.ProductUpdateManyWithoutStoreNestedInput
  Order?: Prisma.OrderUpdateManyWithoutStoreNestedInput
}

export type StoreUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logo?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Product?: Prisma.ProductUncheckedUpdateManyWithoutStoreNestedInput
  Order?: Prisma.OrderUncheckedUpdateManyWithoutStoreNestedInput
}

export type StoreCreateWithoutProductInput = {
  id?: string
  name: string
  description: string
  username: string
  address: string
  status?: string
  isActive?: boolean
  logo: string
  email: string
  contact: string
  createdAt?: Date | string
  updatedAt?: Date | string
  Order?: Prisma.OrderCreateNestedManyWithoutStoreInput
  user: Prisma.UserCreateNestedOneWithoutStoreInput
}

export type StoreUncheckedCreateWithoutProductInput = {
  id?: string
  userId: string
  name: string
  description: string
  username: string
  address: string
  status?: string
  isActive?: boolean
  logo: string
  email: string
  contact: string
  createdAt?: Date | string
  updatedAt?: Date | string
  Order?: Prisma.OrderUncheckedCreateNestedManyWithoutStoreInput
}

export type StoreCreateOrConnectWithoutProductInput = {
  where: Prisma.StoreWhereUniqueInput
  create: Prisma.XOR<Prisma.StoreCreateWithoutProductInput, Prisma.StoreUncheckedCreateWithoutProductInput>
}

export type StoreUpsertWithoutProductInput = {
  update: Prisma.XOR<Prisma.StoreUpdateWithoutProductInput, Prisma.StoreUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.StoreCreateWithoutProductInput, Prisma.StoreUncheckedCreateWithoutProductInput>
  where?: Prisma.StoreWhereInput
}

export type StoreUpdateToOneWithWhereWithoutProductInput = {
  where?: Prisma.StoreWhereInput
  data: Prisma.XOR<Prisma.StoreUpdateWithoutProductInput, Prisma.StoreUncheckedUpdateWithoutProductInput>
}

export type StoreUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logo?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Order?: Prisma.OrderUpdateManyWithoutStoreNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutStoreNestedInput
}

export type StoreUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logo?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Order?: Prisma.OrderUncheckedUpdateManyWithoutStoreNestedInput
}

export type StoreCreateWithoutOrderInput = {
  id?: string
  name: string
  description: string
  username: string
  address: string
  status?: string
  isActive?: boolean
  logo: string
  email: string
  contact: string
  createdAt?: Date | string
  updatedAt?: Date | string
  Product?: Prisma.ProductCreateNestedManyWithoutStoreInput
  user: Prisma.UserCreateNestedOneWithoutStoreInput
}

export type StoreUncheckedCreateWithoutOrderInput = {
  id?: string
  userId: string
  name: string
  description: string
  username: string
  address: string
  status?: string
  isActive?: boolean
  logo: string
  email: string
  contact: string
  createdAt?: Date | string
  updatedAt?: Date | string
  Product?: Prisma.ProductUncheckedCreateNestedManyWithoutStoreInput
}

export type StoreCreateOrConnectWithoutOrderInput = {
  where: Prisma.StoreWhereUniqueInput
  create: Prisma.XOR<Prisma.StoreCreateWithoutOrderInput, Prisma.StoreUncheckedCreateWithoutOrderInput>
}

export type StoreUpsertWithoutOrderInput = {
  update: Prisma.XOR<Prisma.StoreUpdateWithoutOrderInput, Prisma.StoreUncheckedUpdateWithoutOrderInput>
  create: Prisma.XOR<Prisma.StoreCreateWithoutOrderInput, Prisma.StoreUncheckedCreateWithoutOrderInput>
  where?: Prisma.StoreWhereInput
}

export type StoreUpdateToOneWithWhereWithoutOrderInput = {
  where?: Prisma.StoreWhereInput
  data: Prisma.XOR<Prisma.StoreUpdateWithoutOrderInput, Prisma.StoreUncheckedUpdateWithoutOrderInput>
}

export type StoreUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logo?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Product?: Prisma.ProductUpdateManyWithoutStoreNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutStoreNestedInput
}

export type StoreUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logo?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Product?: Prisma.ProductUncheckedUpdateManyWithoutStoreNestedInput
}


/**
 * Count Type StoreCountOutputType
 */

export type StoreCountOutputType = {
  Product: number
  Order: number
}

export type StoreCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Product?: boolean | StoreCountOutputTypeCountProductArgs
  Order?: boolean | StoreCountOutputTypeCountOrderArgs
}

/**
 * StoreCountOutputType without action
 */
export type StoreCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreCountOutputType
   */
  select?: Prisma.StoreCountOutputTypeSelect<ExtArgs> | null
}

/**
 * StoreCountOutputType without action
 */
export type StoreCountOutputTypeCountProductArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
}

/**
 * StoreCountOutputType without action
 */
export type StoreCountOutputTypeCountOrderArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
}


export type StoreSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  description?: boolean
  username?: boolean
  address?: boolean
  status?: boolean
  isActive?: boolean
  logo?: boolean
  email?: boolean
  contact?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  Product?: boolean | Prisma.Store$ProductArgs<ExtArgs>
  Order?: boolean | Prisma.Store$OrderArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.StoreCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["store"]>

export type StoreSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  description?: boolean
  username?: boolean
  address?: boolean
  status?: boolean
  isActive?: boolean
  logo?: boolean
  email?: boolean
  contact?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["store"]>

export type StoreSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  description?: boolean
  username?: boolean
  address?: boolean
  status?: boolean
  isActive?: boolean
  logo?: boolean
  email?: boolean
  contact?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["store"]>

export type StoreSelectScalar = {
  id?: boolean
  userId?: boolean
  name?: boolean
  description?: boolean
  username?: boolean
  address?: boolean
  status?: boolean
  isActive?: boolean
  logo?: boolean
  email?: boolean
  contact?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type StoreOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "name" | "description" | "username" | "address" | "status" | "isActive" | "logo" | "email" | "contact" | "createdAt" | "updatedAt", ExtArgs["result"]["store"]>
export type StoreInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Product?: boolean | Prisma.Store$ProductArgs<ExtArgs>
  Order?: boolean | Prisma.Store$OrderArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.StoreCountOutputTypeDefaultArgs<ExtArgs>
}
export type StoreIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type StoreIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $StorePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Store"
  objects: {
    Product: Prisma.$ProductPayload<ExtArgs>[]
    Order: Prisma.$OrderPayload<ExtArgs>[]
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    name: string
    description: string
    username: string
    address: string
    status: string
    isActive: boolean
    logo: string
    email: string
    contact: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["store"]>
  composites: {}
}

export type StoreGetPayload<S extends boolean | null | undefined | StoreDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StorePayload, S>

export type StoreCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StoreFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StoreCountAggregateInputType | true
  }

export interface StoreDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Store'], meta: { name: 'Store' } }
  /**
   * Find zero or one Store that matches the filter.
   * @param {StoreFindUniqueArgs} args - Arguments to find a Store
   * @example
   * // Get one Store
   * const store = await prisma.store.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StoreFindUniqueArgs>(args: Prisma.SelectSubset<T, StoreFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StoreClient<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Store that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StoreFindUniqueOrThrowArgs} args - Arguments to find a Store
   * @example
   * // Get one Store
   * const store = await prisma.store.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StoreFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StoreFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StoreClient<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Store that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreFindFirstArgs} args - Arguments to find a Store
   * @example
   * // Get one Store
   * const store = await prisma.store.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StoreFindFirstArgs>(args?: Prisma.SelectSubset<T, StoreFindFirstArgs<ExtArgs>>): Prisma.Prisma__StoreClient<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Store that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreFindFirstOrThrowArgs} args - Arguments to find a Store
   * @example
   * // Get one Store
   * const store = await prisma.store.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StoreFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StoreFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StoreClient<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Stores that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Stores
   * const stores = await prisma.store.findMany()
   * 
   * // Get first 10 Stores
   * const stores = await prisma.store.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const storeWithIdOnly = await prisma.store.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StoreFindManyArgs>(args?: Prisma.SelectSubset<T, StoreFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Store.
   * @param {StoreCreateArgs} args - Arguments to create a Store.
   * @example
   * // Create one Store
   * const Store = await prisma.store.create({
   *   data: {
   *     // ... data to create a Store
   *   }
   * })
   * 
   */
  create<T extends StoreCreateArgs>(args: Prisma.SelectSubset<T, StoreCreateArgs<ExtArgs>>): Prisma.Prisma__StoreClient<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Stores.
   * @param {StoreCreateManyArgs} args - Arguments to create many Stores.
   * @example
   * // Create many Stores
   * const store = await prisma.store.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StoreCreateManyArgs>(args?: Prisma.SelectSubset<T, StoreCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Stores and returns the data saved in the database.
   * @param {StoreCreateManyAndReturnArgs} args - Arguments to create many Stores.
   * @example
   * // Create many Stores
   * const store = await prisma.store.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Stores and only return the `id`
   * const storeWithIdOnly = await prisma.store.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StoreCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StoreCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Store.
   * @param {StoreDeleteArgs} args - Arguments to delete one Store.
   * @example
   * // Delete one Store
   * const Store = await prisma.store.delete({
   *   where: {
   *     // ... filter to delete one Store
   *   }
   * })
   * 
   */
  delete<T extends StoreDeleteArgs>(args: Prisma.SelectSubset<T, StoreDeleteArgs<ExtArgs>>): Prisma.Prisma__StoreClient<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Store.
   * @param {StoreUpdateArgs} args - Arguments to update one Store.
   * @example
   * // Update one Store
   * const store = await prisma.store.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StoreUpdateArgs>(args: Prisma.SelectSubset<T, StoreUpdateArgs<ExtArgs>>): Prisma.Prisma__StoreClient<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Stores.
   * @param {StoreDeleteManyArgs} args - Arguments to filter Stores to delete.
   * @example
   * // Delete a few Stores
   * const { count } = await prisma.store.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StoreDeleteManyArgs>(args?: Prisma.SelectSubset<T, StoreDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Stores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Stores
   * const store = await prisma.store.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StoreUpdateManyArgs>(args: Prisma.SelectSubset<T, StoreUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Stores and returns the data updated in the database.
   * @param {StoreUpdateManyAndReturnArgs} args - Arguments to update many Stores.
   * @example
   * // Update many Stores
   * const store = await prisma.store.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Stores and only return the `id`
   * const storeWithIdOnly = await prisma.store.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StoreUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StoreUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Store.
   * @param {StoreUpsertArgs} args - Arguments to update or create a Store.
   * @example
   * // Update or create a Store
   * const store = await prisma.store.upsert({
   *   create: {
   *     // ... data to create a Store
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Store we want to update
   *   }
   * })
   */
  upsert<T extends StoreUpsertArgs>(args: Prisma.SelectSubset<T, StoreUpsertArgs<ExtArgs>>): Prisma.Prisma__StoreClient<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Stores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreCountArgs} args - Arguments to filter Stores to count.
   * @example
   * // Count the number of Stores
   * const count = await prisma.store.count({
   *   where: {
   *     // ... the filter for the Stores we want to count
   *   }
   * })
  **/
  count<T extends StoreCountArgs>(
    args?: Prisma.Subset<T, StoreCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StoreCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Store.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StoreAggregateArgs>(args: Prisma.Subset<T, StoreAggregateArgs>): Prisma.PrismaPromise<GetStoreAggregateType<T>>

  /**
   * Group by Store.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StoreGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StoreGroupByArgs['orderBy'] }
      : { orderBy?: StoreGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StoreGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStoreGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Store model
 */
readonly fields: StoreFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Store.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StoreClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Product<T extends Prisma.Store$ProductArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Store$ProductArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Order<T extends Prisma.Store$OrderArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Store$OrderArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Store model
 */
export interface StoreFieldRefs {
  readonly id: Prisma.FieldRef<"Store", 'String'>
  readonly userId: Prisma.FieldRef<"Store", 'String'>
  readonly name: Prisma.FieldRef<"Store", 'String'>
  readonly description: Prisma.FieldRef<"Store", 'String'>
  readonly username: Prisma.FieldRef<"Store", 'String'>
  readonly address: Prisma.FieldRef<"Store", 'String'>
  readonly status: Prisma.FieldRef<"Store", 'String'>
  readonly isActive: Prisma.FieldRef<"Store", 'Boolean'>
  readonly logo: Prisma.FieldRef<"Store", 'String'>
  readonly email: Prisma.FieldRef<"Store", 'String'>
  readonly contact: Prisma.FieldRef<"Store", 'String'>
  readonly createdAt: Prisma.FieldRef<"Store", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Store", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Store findUnique
 */
export type StoreFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreInclude<ExtArgs> | null
  /**
   * Filter, which Store to fetch.
   */
  where: Prisma.StoreWhereUniqueInput
}

/**
 * Store findUniqueOrThrow
 */
export type StoreFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreInclude<ExtArgs> | null
  /**
   * Filter, which Store to fetch.
   */
  where: Prisma.StoreWhereUniqueInput
}

/**
 * Store findFirst
 */
export type StoreFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreInclude<ExtArgs> | null
  /**
   * Filter, which Store to fetch.
   */
  where?: Prisma.StoreWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stores to fetch.
   */
  orderBy?: Prisma.StoreOrderByWithRelationInput | Prisma.StoreOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Stores.
   */
  cursor?: Prisma.StoreWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Stores.
   */
  distinct?: Prisma.StoreScalarFieldEnum | Prisma.StoreScalarFieldEnum[]
}

/**
 * Store findFirstOrThrow
 */
export type StoreFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreInclude<ExtArgs> | null
  /**
   * Filter, which Store to fetch.
   */
  where?: Prisma.StoreWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stores to fetch.
   */
  orderBy?: Prisma.StoreOrderByWithRelationInput | Prisma.StoreOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Stores.
   */
  cursor?: Prisma.StoreWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Stores.
   */
  distinct?: Prisma.StoreScalarFieldEnum | Prisma.StoreScalarFieldEnum[]
}

/**
 * Store findMany
 */
export type StoreFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreInclude<ExtArgs> | null
  /**
   * Filter, which Stores to fetch.
   */
  where?: Prisma.StoreWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stores to fetch.
   */
  orderBy?: Prisma.StoreOrderByWithRelationInput | Prisma.StoreOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Stores.
   */
  cursor?: Prisma.StoreWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stores.
   */
  skip?: number
  distinct?: Prisma.StoreScalarFieldEnum | Prisma.StoreScalarFieldEnum[]
}

/**
 * Store create
 */
export type StoreCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreInclude<ExtArgs> | null
  /**
   * The data needed to create a Store.
   */
  data: Prisma.XOR<Prisma.StoreCreateInput, Prisma.StoreUncheckedCreateInput>
}

/**
 * Store createMany
 */
export type StoreCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Stores.
   */
  data: Prisma.StoreCreateManyInput | Prisma.StoreCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Store createManyAndReturn
 */
export type StoreCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * The data used to create many Stores.
   */
  data: Prisma.StoreCreateManyInput | Prisma.StoreCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Store update
 */
export type StoreUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreInclude<ExtArgs> | null
  /**
   * The data needed to update a Store.
   */
  data: Prisma.XOR<Prisma.StoreUpdateInput, Prisma.StoreUncheckedUpdateInput>
  /**
   * Choose, which Store to update.
   */
  where: Prisma.StoreWhereUniqueInput
}

/**
 * Store updateMany
 */
export type StoreUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Stores.
   */
  data: Prisma.XOR<Prisma.StoreUpdateManyMutationInput, Prisma.StoreUncheckedUpdateManyInput>
  /**
   * Filter which Stores to update
   */
  where?: Prisma.StoreWhereInput
  /**
   * Limit how many Stores to update.
   */
  limit?: number
}

/**
 * Store updateManyAndReturn
 */
export type StoreUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * The data used to update Stores.
   */
  data: Prisma.XOR<Prisma.StoreUpdateManyMutationInput, Prisma.StoreUncheckedUpdateManyInput>
  /**
   * Filter which Stores to update
   */
  where?: Prisma.StoreWhereInput
  /**
   * Limit how many Stores to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Store upsert
 */
export type StoreUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreInclude<ExtArgs> | null
  /**
   * The filter to search for the Store to update in case it exists.
   */
  where: Prisma.StoreWhereUniqueInput
  /**
   * In case the Store found by the `where` argument doesn't exist, create a new Store with this data.
   */
  create: Prisma.XOR<Prisma.StoreCreateInput, Prisma.StoreUncheckedCreateInput>
  /**
   * In case the Store was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StoreUpdateInput, Prisma.StoreUncheckedUpdateInput>
}

/**
 * Store delete
 */
export type StoreDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreInclude<ExtArgs> | null
  /**
   * Filter which Store to delete.
   */
  where: Prisma.StoreWhereUniqueInput
}

/**
 * Store deleteMany
 */
export type StoreDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Stores to delete
   */
  where?: Prisma.StoreWhereInput
  /**
   * Limit how many Stores to delete.
   */
  limit?: number
}

/**
 * Store.Product
 */
export type Store$ProductArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  cursor?: Prisma.ProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * Store.Order
 */
export type Store$OrderArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  cursor?: Prisma.OrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * Store without action
 */
export type StoreDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreInclude<ExtArgs> | null
}
